[project]
name = "chartink"
version = "0.1.0"
description = "Chartink scanner results fetcher and analyzer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "selenium>=4.38.0",
]
